CREATE TABLE [Fact].[Purchase_Orders] (
    [Purchase_Order_Key]                    INT             IDENTITY (1, 1) NOT NULL,
    [Purchase_Order_Number]                 VARCHAR (50)    NOT NULL,
    [Purchase_Order_Line_Number]            INT             NOT NULL,
    [Invent_Trans_ID]                       VARCHAR (20)    NOT NULL,
    [Delivery_Location_Key]                 INT             NULL,
    [Vendor_Key]                            SMALLINT        NULL,
    [Purchase_Order_Property_Key]           SMALLINT        NULL,
    [Product_Key]                           INT             NULL,
    [Purchase_Order_Fill_Key]               TINYINT         NULL,
    [Purchase_Order_Name]                   VARCHAR (100)   NOT NULL,
    [Purchase_Line_Description]             VARCHAR (1000)  NOT NULL,
    [Purchase_Order_Header_Accounting_Date] DATE            NULL,
    [Purchase_Line_Confirmed_Delivery_Date] DATE            NULL,
    [Purchase_Line_Requested_Delivery_Date] DATE            NULL,
    [Purchase_Line_Confirmed_Shipping_Date] DATE            NULL,
    [Purchase_Line_Requested_Shipping_Date] DATE            NULL,
    [Purchase_Line_Amount]                  NUMERIC (32, 6) NOT NULL,
    [Purchase_Line_Open_Amount]             AS              ([Purchase_Line_Purchase_Price]*case when [Received_Quantity]>[Purchase_Line_Ordered_Quantity] then (0) else [Purchase_Line_Ordered_Quantity]-[Received_Quantity] end),
    [Purchase_Line_Received_Amount]         AS              ([Purchase_Line_Purchase_Price]*[Received_Quantity]),
    [Purchase_Line_Overfill_Amount]         AS              ([Purchase_Line_Purchase_Price]*case when [Received_Quantity]>[Purchase_Line_Ordered_Quantity] then [Received_Quantity]-[Purchase_Line_Ordered_Quantity] else (0) end),
    [Purchase_Line_Purchase_Price]          NUMERIC (32, 6) NOT NULL,
    [Purchase_Line_Discount_Amount]         NUMERIC (32, 6) NOT NULL,
    [Purchase_Line_Price_Quantity]          SMALLINT        NULL,
    [Purchase_Line_Ordered_Quantity]        SMALLINT        NULL,
    [Received_Quantity]                     SMALLINT        NULL,
    [Open_Quantity]                         AS              (case when [Received_Quantity]>[Purchase_Line_Ordered_Quantity] then (0) else [Purchase_Line_Ordered_Quantity]-[Received_Quantity] end),
    [Overfill_Quantity]                     AS              (case when [Received_Quantity]>[Purchase_Line_Ordered_Quantity] then [Received_Quantity]-[Purchase_Line_Ordered_Quantity] else (0) end),
    [Commission_Charge_Percentage]          NUMERIC (10, 6) NULL,
    [Tariff_Charge_Percentage]              NUMERIC (10, 6) NULL,
    [Duty_Charge_Percentage]                NUMERIC (10, 6) NULL,
    [Freight_Charge_Percentage]             NUMERIC (10, 6) NULL,
    [Freight_In_Charge_Percentage]          NUMERIC (10, 6) NULL,
    [Commission_Charge_Amount]              AS              ((([Commission_Charge_Percentage]/(100))*[Purchase_Line_Purchase_Price])*[Purchase_Line_Ordered_Quantity]),
    [Tariff_Charge_Amount]                  AS              ((([Tariff_Charge_Percentage]/(100))*[Purchase_Line_Purchase_Price])*[Purchase_Line_Ordered_Quantity]),
    [Duty_Charge_Amount]                    AS              ((([Duty_Charge_Percentage]/(100))*[Purchase_Line_Purchase_Price])*[Purchase_Line_Ordered_Quantity]),
    [Freight_Charge_Amount]                 AS              ((([Freight_Charge_Percentage]/(100))*[Purchase_Line_Purchase_Price])*[Purchase_Line_Ordered_Quantity]),
    [Freight_In_Charge_Amount]              AS              ((([Freight_In_Charge_Percentage]/(100))*[Purchase_Line_Purchase_Price])*[Purchase_Line_Ordered_Quantity]),
    [First_Cost]                            AS              ([Purchase_Line_Purchase_Price]*[Purchase_Line_Ordered_Quantity]),
    [Vendor_Packing_Slip_Count]             TINYINT         NULL,
    [Barcode]                               VARCHAR (80)    NULL,
    [is_Removed_From_Source]                BIT             NULL,
    [is_Excluded]                           BIT             NULL,
    [ETL_Created_Date]                      DATETIME2 (5)   NULL,
    [ETL_Modified_Date]                     DATETIME2 (5)   NULL,
    [ETL_Modified_Count]                    SMALLINT        NULL,
    CONSTRAINT [PK_Purchase_Orders] PRIMARY KEY CLUSTERED ([Purchase_Order_Key] ASC),
    CONSTRAINT [UK_Purchase_Orders] UNIQUE NONCLUSTERED ([Purchase_Order_Number] ASC, [Purchase_Order_Line_Number] ASC)
);

