CREATE LOGIN [dgutnik]
    WITH PASSWORD = N'lxdWzjwV:aBZy1gffwhjtzhomsFT7_&#$!~<itxghoPplctp', SID = 0xDCEBBC5D9CAD1A4DAA91C01F7594C3AB, DEFAULT_DATABASE = [AX_PRODUCTION], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

